package entity

import (
	"time"

	"github.com/kevinsoras/GoCleanDDD/internal/silicon/shared/utils"
)

type PersonDetail interface {
	Validate() error
	GetID() string
	GetType() PersonType
}

type Person struct {
	ID        string
	Type      PersonType
	Status    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewCreatePerson initializes a new Person for creation
func NewCreatePerson(personType PersonType) *Person {
	now := time.Now()
	return &Person{
		ID:        utils.GenerateUUID(), // Will be generated by DB or UUID generator
		Type:      personType,
		Status:    true,
		CreatedAt: now,
		UpdatedAt: now,
	}
}
